import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create.xyz App',
  description: 'Generated by create.xyz',
};


export default function RootLayout({ children }) {
  console.log("RootLayout laddas"); // <--- tillfällig debug
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
